apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"
  steps:
    - name: create-venv
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "Creating virtual environment..."
        python -m venv venv
        source venv/bin/activate
        echo "Upgrading pip inside the virtual environment..."
        python -m pip install --upgrade pip wheel
    - name: install-dependencies
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "Activating virtual environment and installing dependencies..."
        source venv/bin/activate
        pip install -r requirements.txt
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "Running tests inside virtual environment..."
        source venv/bin/activate
        nosetests $(params.args)
